### ISSUE TITLE
Design notifications window

### ISSUE THREAD

**Issue by esanchezdevel** [esanchezdevel/breaks-counter#5]
> estimate 1
> real time spent 0.41
> remaining 2023-10-05 0.31
> remaining 2023-10-06 0.21
> remaining 2023-10-07 0.01
> remaining 2023-10-09 0

**Description:**
I have to design the frontend of the Notification window

**Tasks to do:**
- [x] Place message in the center of the window
- [x] Find gif images to use
- [x] Place gif images in the window
- [x] Show window in the top of all other windows
- [x] Close window after 30seconds

**Comment by esanchezdevel** [comment]
Hi, 

Issue closed after add all expected changes in ``develop`` branch.

Thanks!
