### ISSUE TITLE
Create executable file

### ISSUE THREAD

**Issue by esanchezdevel** [esanchezdevel/breaks-counter#7]
> estimate 0.5

**Description:**
I have to compile the project and create the executable file to run the application

**Tasks to do:**
- [x] Add principal class to manifest
- [x] Create stable release version
- [x] Tag commit in ``main`` branch with stable version
- [x] Create the executable file

**Comment by esanchezdevel** [comment]
Closing issue after create the stable version.
